/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LicensingRouteImport } from './routes/licensing'
import { Route as MyLibraryRouteImport } from './routes/my-library'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as AccountSettingsRouteImport } from './routes/account.settings'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as GuidesSlugRouteImport } from './routes/guides_.$slug'
import { Route as ResourcesSlugRouteImport } from './routes/resources_.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensingRoute = LicensingRouteImport.update({
  id: '/licensing',
  path: '/licensing',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLibraryRoute = MyLibraryRouteImport.update({
  id: '/my-library',
  path: '/my-library',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides_/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources_/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/favorites': typeof FavoritesRoute
  '/gallery': typeof GalleryRoute
  '/guides': typeof GuidesRoute
  '/help': typeof HelpRoute
  '/library': typeof LibraryRoute
  '/licensing': typeof LicensingRoute
  '/my-library': typeof MyLibraryRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/refunds': typeof RefundsRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unlock': typeof UnlockRoute
  '/account/settings': typeof AccountSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/favorites': typeof FavoritesRoute
  '/gallery': typeof GalleryRoute
  '/guides': typeof GuidesRoute
  '/help': typeof HelpRoute
  '/library': typeof LibraryRoute
  '/licensing': typeof LicensingRoute
  '/my-library': typeof MyLibraryRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/refunds': typeof RefundsRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unlock': typeof UnlockRoute
  '/account/settings': typeof AccountSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/favorites': typeof FavoritesRoute
  '/gallery': typeof GalleryRoute
  '/guides': typeof GuidesRoute
  '/help': typeof HelpRoute
  '/library': typeof LibraryRoute
  '/licensing': typeof LicensingRoute
  '/my-library': typeof MyLibraryRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/refunds': typeof RefundsRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unlock': typeof UnlockRoute
  '/account/settings': typeof AccountSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/guides_/$slug': typeof GuidesSlugRoute
  '/resources_/$slug': typeof ResourcesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/downloads'
    | '/favorites'
    | '/gallery'
    | '/guides'
    | '/help'
    | '/library'
    | '/licensing'
    | '/my-library'
    | '/notifications'
    | '/profile'
    | '/refunds'
    | '/resources'
    | '/sitemap.xml'
    | '/terms'
    | '/unlock'
    | '/account/settings'
    | '/auth/callback'
    | '/guides/$slug'
    | '/resources/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/downloads'
    | '/favorites'
    | '/gallery'
    | '/guides'
    | '/help'
    | '/library'
    | '/licensing'
    | '/my-library'
    | '/notifications'
    | '/profile'
    | '/refunds'
    | '/resources'
    | '/sitemap.xml'
    | '/terms'
    | '/unlock'
    | '/account/settings'
    | '/auth/callback'
    | '/guides/$slug'
    | '/resources/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/downloads'
    | '/favorites'
    | '/gallery'
    | '/guides'
    | '/help'
    | '/library'
    | '/licensing'
    | '/my-library'
    | '/notifications'
    | '/profile'
    | '/refunds'
    | '/resources'
    | '/sitemap.xml'
    | '/terms'
    | '/unlock'
    | '/account/settings'
    | '/auth/callback'
    | '/guides_/$slug'
    | '/resources_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DownloadsRoute: typeof DownloadsRoute
  FavoritesRoute: typeof FavoritesRoute
  GalleryRoute: typeof GalleryRoute
  GuidesRoute: typeof GuidesRoute
  HelpRoute: typeof HelpRoute
  LibraryRoute: typeof LibraryRoute
  LicensingRoute: typeof LicensingRoute
  MyLibraryRoute: typeof MyLibraryRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RefundsRoute: typeof RefundsRoute
  ResourcesRoute: typeof ResourcesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UnlockRoute: typeof UnlockRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licensing': {
      id: '/licensing'
      path: '/licensing'
      fullPath: '/licensing'
      preLoaderRoute: typeof LicensingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-library': {
      id: '/my-library'
      path: '/my-library'
      fullPath: '/my-library'
      preLoaderRoute: typeof MyLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides_/$slug': {
      id: '/guides_/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources_/$slug': {
      id: '/resources_/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DownloadsRoute: DownloadsRoute,
  FavoritesRoute: FavoritesRoute,
  GalleryRoute: GalleryRoute,
  GuidesRoute: GuidesRoute,
  HelpRoute: HelpRoute,
  LibraryRoute: LibraryRoute,
  LicensingRoute: LicensingRoute,
  MyLibraryRoute: MyLibraryRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RefundsRoute: RefundsRoute,
  ResourcesRoute: ResourcesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UnlockRoute: UnlockRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
