/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'

const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/guides': typeof GuidesRouteWithChildren
  '/library': typeof LibraryRoute
  '/resources': typeof ResourcesRoute
  '/guides/$slug': typeof GuidesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/guides': typeof GuidesRouteWithChildren
  '/library': typeof LibraryRoute
  '/resources': typeof ResourcesRoute
  '/guides/$slug': typeof GuidesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/guides': typeof GuidesRouteWithChildren
  '/library': typeof LibraryRoute
  '/resources': typeof ResourcesRoute
  '/guides/$slug': typeof GuidesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/guides'
    | '/library'
    | '/resources'
    | '/guides/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/guides'
    | '/library'
    | '/resources'
    | '/guides/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/guides'
    | '/library'
    | '/resources'
    | '/guides/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  LibraryRoute: typeof LibraryRoute
  ResourcesRoute: typeof ResourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
  }
}

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GuidesRoute: GuidesRouteWithChildren,
  LibraryRoute: LibraryRoute,
  ResourcesRoute: ResourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
